### ISSUE TITLE
Needs a has_archive flag

### ISSUE THREAD

**Issue by isarmstrong** [jjgrainger/wp-custom-post-type-class#26]
I frequently disable the CPT archive and use a custom page template instead - basically any time the classic blog list format doesn't apply.

Will try to hack it in real quick but if I submit a pull request, it may not be how you'd do it within your structure.

**Comment by QWp6t** [comment]
lolwut

```php
$books = new CPT('book', array(
    // blah blah blah, options here
    'has_archive' => false
));
```

Does that not work for you?

**Comment by jjgrainger** [comment]
@QWp6t example should work,

The class constructor accepts two parameters, which practically mimic the `register_post_type` ([codex](http://codex.wordpress.org/Function_Reference/register_post_type#Parameters)) function with Wordpress.

The second parameter is the arguments for the post type, which accepts the exact same options listed for the `register_post_type` function. This includes the `has_archive` option.

@isarmstrong could you double check the above example works for you, so we know its not a bug, thanks.

:)

**Comment by isarmstrong** [comment]
Yeah I'll double check. Pretty sure that was the first thing I tried.

I suspect the problem is that I initialize a theme using an init class,
hooked to after_theme_setup. Putting the class inside a class was probably
creating unpredictable results.

I'll replicate it when my week slows down a bit.

**Comment by kalenjohnson** [comment]
@isarmstrong `new CPT()` should not be included in a hook, it sets up the hooks in `__construct`, so if you are using `CPT` in a hook then it's probably not working at all and being loaded too late.

**Comment by jjgrainger** [comment]
@kalenjohnson is correct, placing your `CPT` code inside another action will create problems
