### ISSUE TITLE
Supports does not seem to be working

### ISSUE THREAD

**Issue by isarmstrong** [jjgrainger/wp-custom-post-type-class#27]
Looks like you didn't add it to the constructor.

**Comment by QWp6t** [comment]
I think you're not using this class correctly. Or you're calling it too late. You need to be calling it before `init` is fired. Also make sure you're passing in the first parameter.

```php
$books = new CPT('book', array(
    'supports' => array('title', 'editor', 'thumbnail', 'comments')
));
```

**Comment by isarmstrong** [comment]
That would be the problem. I was calling it inside a setup theme function on after_setup_theme

**Comment by jjgrainger** [comment]
Yeah,

The class registers everything at the correct times with `add_action` etc, so theres no need to call the class and its methods inside more actions.
