### ISSUE TITLE
Register taxonomies first?

### ISSUE THREAD

**Issue by FriendlyWP** [jjgrainger/wp-custom-post-type-class#28]
Thanks for this class, very useful!

One note, in order to ensure taxonomy permalinks always work, it's useful to switch lines 168 and 171, so that the taxonomies are registered first. Bizarre but true, see this post: http://clarknikdelpowell.com/blog/the-right-way-to-do-wordpress-custom-taxonomy-rewrites/

In the current configuration, taxonomy slugs that include a path ("books/genre") instead of just a simple slug ("genre") get created correctly, but result in 404's when you surf to them. Swap so taxonomies are registered first, and they work.

**Comment by jjgrainger** [comment]
Interesting! I'll get to this today/tomorrow when I get 5mins.

Thanks :)
