### ISSUE TITLE
Custom capabilities in CPT

### ISSUE THREAD

**Issue by q2amarket** [jjgrainger/wp-custom-post-type-class#30]
It's nice class. However, it could be even better by adding custom capabilities option. Are you planning or give some sort of idea to add it?

**Comment by jjgrainger** [comment]
This can be achieved through the second parameter passed when constructing the post type with the class ([codex](http://codex.wordpress.org/Function_Reference/register_post_type#Parameters)). example:

```php
$books = new CPT('book', array(
    'capability_type' => array('book', 'books'),
    'map_meta_cap' => true
));
```

There are other arguments such as `capabilities` which the above will build automatically for you. It's just how you assign the new custom capabilities to the different user roles within WordPress there after. (example here: [stackoverflow](http://wordpress.stackexchange.com/questions/108338/capabilities-and-custom-post-types))

At first glance, I can't imagine a way the class would be able to do this that is simple and easy to use while also being flexible enough to allow for a variety of situations? I don't know.

Still it would be worth looking into.

**Comment by q2amarket** [comment]
Yeah I realized that later I open an issue. Thanks a lot for nice library...!
