### ISSUE TITLE
v1.3.2 error

### ISSUE THREAD

**Issue by deadlyhifi** [jjgrainger/wp-custom-post-type-class#37]
I've just upgraded to v1.3.2 and am seeing the following error.

`Warning: Invalid argument supplied for foreach() in /var/www/project/vendor/jjgrainger/wp-custom-post-type-class/src/CPT.php on line 568`

**Comment by jjgrainger** [comment]
Thats annoying,

I've missed out a simple `if( is_array( $this->existing_taxonomies ) )` before looping through the array :(

Thanks for bringing it up, I'll get this fixed now :)

**Comment by deadlyhifi** [comment]
No problem, thanks for the quick fix.
