### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by vinkla** [jjgrainger/wp-custom-post-type-class#38]
We're getting a `Invalid argument supplied for foreach()` on line 568. We've just updated to the latest version released yesterday `1.3.2`.

**Comment by jjgrainger** [comment]
This has been fixed in the latest release `1.3.3`, see #37 

Though, I've just realised I haven't formally made `1.3.3` a release

I'll do that now

**Comment by vinkla** [comment]
Awesome!
