### ISSUE TITLE
PHP Warning in add_admin_columns

### ISSUE THREAD

**Issue by swhinnem** [jjgrainger/wp-custom-post-type-class#39]
I'm getting the following warnings:

`PHP Warning:  in_array() expects parameter 2 to be array, null given in [theme]/inc/CPT.php on line 591`
`PHP Warning:  in_array() expects parameter 2 to be array, null given in [theme]/inc/CPT.php on line 593`

I'm just using this in a pretty basic way, not adding any taxonomies to my CPT. Should this check if there are any taxonomies to work with earlier? (currently does this on :611)

**Comment by jjgrainger** [comment]
Yeah, I've missed out a check again,

Thanks, I'll get this fixed :)

**Comment by swhinnem** [comment]
:boom: 

BTW, this is awesome and super useful. Thanks for your work on it

**Comment by hansott** [comment]
@jjgrainger You could initialize the taxonomies property as an empty array or like you said place extra checks on those lines. :-)

**Comment by hansott** [comment]
+1

**Comment by hansott** [comment]
To fix this:

Changed line 591 from
`if ( in_array( 'post_tag', $this->taxonomies ) || $this->post_type_name === 'post' ) {`
To
`if ( ( is_array( $this->taxonomies ) && in_array( 'post_tag', $this->taxonomies ) ) || $this->post_type_name === 'post' ) {`

Changed line 593 from
`} elseif( in_array( 'category', $this->taxonomies ) || $this->post_type_name === 'post' ) {`
To
`} elseif( ( is_array( $this->taxonomies ) && in_array( 'category', $this->taxonomies ) ) || $this->post_type_name === 'post' ) {`

**Comment by jjgrainger** [comment]
Thanks,

I have put this together already [in this branch](https://github.com/jjgrainger/wp-custom-post-type-class/tree/fix-add-admin-columns-error) ([this commit here](https://github.com/jjgrainger/wp-custom-post-type-class/commit/26e321c298e74a14b041e94a07812ea40763d22b)), but just haven't merged the changes in yet.

The last couple of releases have only been very minor fixes, so I was hoping to add a couple of extra features and update the doc's in the next release.

Should hopefully get this done soon!

:)

**Comment by hansott** [comment]
Cool! :smile:

**Comment by swhinnem** [comment]
Is this fix going to change the way the if logic works? Before, it was `if ( A || B )`, and now it's 
`if ( C && A || B)`. Shouldn't it be `if ( C && ( A || B ) )`. Does the order of operations here matter? (FD: I didn't read too much of the surrounding code)

**Comment by jjgrainger** [comment]
I had to go over this a few times just to be sure, but yes the logic is correct... I think! 

I'm not sure now :P

To be honest that whole method isn't very well implemented and should be refactored, for starters initialising the `$taxonomies` property as an array as @hansott mentioned, would solve a lot of the issues.

**Comment by swhinnem** [comment]
Just checking, SGTM! :+1:
