### ISSUE TITLE
Call to undefined function array

### ISSUE THREAD

**Issue by JKD2015** [jjgrainger/wp-custom-post-type-class#40]
This showed up in a deploy to a wordpress site, but I have deployed same to other servers without this error...

Fatal error: Call to undefined function array_replace_recursive() in /home/content/j/o/s/sitenamehere/html/wp-content/themes/themename/inc/post-types/CPT.php on line 512

**Comment by jjgrainger** [comment]
`array_replace_recursive()` is part of PHP version 5.3+, so its likely the PHP version isn't high enough on that server.

If you don't want to don't want to mess around with PHP version on the server, you can use [this function](http://stackoverflow.com/questions/2874035/php-array-replace-recursive-alternative).

I've used it before and it seems to do the job.

Let me know how you get on :)

**Comment by JKD2015** [comment]
thanks...
