### ISSUE TITLE
Custom labels

### ISSUE THREAD

**Issue by mustardBees** [jjgrainger/wp-custom-post-type-class#42]
I don't believe this is currently possible. It'd be useful to be able to override the default post type labels. I often like to set a custom menu_name for example.

**Comment by jjgrainger** [comment]
This can be done (unless there's a bug).

When creating a post type the second argument accepts the exact same arguments as when registering a post type with [`register_post_type()`](http://codex.wordpress.org/Function_Reference/register_post_type#Arguments).

Here you can define any of the labels you want. For example, if you had a post type called 'books' and wanted the menu name to be 'library', you could do the following:

```php
$library = new CPT('book', array(
    'labels' => array(
        'menu_name' => 'Library'
    )
));
```

Let me know how you get on :)

**Comment by mustardBees** [comment]
Hey @jjgrainger - I stand corrected, and thank you for the example! :)

**Comment by jjgrainger** [comment]
No worries, enjoy! :)
