### ISSUE TITLE
Idea - Add extra fields in taxonomy

### ISSUE THREAD

**Issue by 3runoDesign** [jjgrainger/wp-custom-post-type-class#44]
It would be nice to add extra fields to a taxonomy.

https://gist.github.com/3runoDesign/7b438e85756b8a3ca4f6

**Comment by jjgrainger** [comment]
I've avoided making anything to do with custom fields for both post types and taxonomies as [Advanced Custom Fields](http://www.advancedcustomfields.com/) plugin does a great job at this already and more.

**Comment by 3runoDesign** [comment]
I understand. But I refer to the fields of taxonomy, not a post linked to one taxonomy.

**Comment by jjgrainger** [comment]
Yes, with Advanced Custom Fields plugin you can create custom fields for taxonomies and more.

I hope I'm understanding you correctly?

**Comment by 3runoDesign** [comment]
trans

**Comment by 3runoDesign** [comment]
Really ECF already do what I wanted to do.

http://www.advancedcustomfields.com/resources/get-values-from-a-taxonomy-term/

:+1:

**Comment by jjgrainger** [comment]
:+1: Glad you got it all working :)
