### ISSUE TITLE
Issuse: Atribute panel no showing parent select

### ISSUE THREAD

**Issue by RaulGomezFrontEnd** [jjgrainger/wp-custom-post-type-class#45]
First of all thx for the code :)

When the custom post is created i can´t get the hierarchy to work properly.

![image](https://cloud.githubusercontent.com/assets/8059209/9846308/97d14462-5ad1-11e5-8460-98f9a35b5258.png)

The 'Parent' select does not show up ( And yes, i do have more than one post of the same post-type )

![image](https://cloud.githubusercontent.com/assets/8059209/9846360/039abaac-5ad2-11e5-82a3-521e09bd5bea.png)

Thanks for all.

**Comment by jjgrainger** [comment]
I've just run a couple of test cases and managed to get it working.

It would be good if you could show some code, just to double check what you've done.

From your screenshots it seems though you have set most thing setup correctly, but as a starting point, things I usually get wrong when trying to get the post parent to work:

* spelling **hierarchical** wrong
* making sure that `page-attributes` is in the `supports` array
* having at least 1 post published (to be able to select a parent)

If you could drop in the code you've used just so I can get a better idea of whats going on that would be great, thanks

:)

**Comment by RaulGomezFrontEnd** [comment]
Hi Joe.

This is the code

$master = new CPT(
array(
'post_type_name' => 'masters',
'singular'       => __( 'Master', 'ide' ),
'plural'         => __( 'Masters', 'ide' ),
'slug'           => 'masters'
),

array(
'supports'  => array( 'title', 'editor', 'thumbnail', 'excerpt',
'custom-fields', 'comments', 'page-attributes' ),
'menu_icon' => 'dashicons-portfolio'
)
);

$master -> register_taxonomy(
array(
'taxonomy_name' => 'masters_tags',
'singular'      => __( 'Master Tag', 'ide-cesem' ),
'plural'        => __( 'Masters Tags', 'ide-cesem' ),
'slug'          => 'masters-tag'
)
);


and yes i have more than one post.


Thanks for taking some time to help me out.

2015-09-14 12:04 GMT+02:00 Joe Grainger <notifications@github.com>:

**Comment by jjgrainger** [comment]
Thanks,

could you try adding modifying the second array in the CPT call to...

```php
array(
    'supports'  => array( 'title', 'editor', 'thumbnail', 'excerpt',
    'custom-fields', 'comments', 'page-attributes' ), 
    'menu_icon' => 'dashicons-portfolio',
    'hierarchical' => true // just the addition of this
)
```

Let me know if that helps,

Thanks :)

**Comment by RaulGomezFrontEnd** [comment]
i´ve changed the code as u suggested and still the same, no parent selector
shows up.

$master = new CPT(
array(
'post_type_name' => 'masters',
'singular'       => __( 'Master', 'ide' ),
'plural'         => __( 'Masters', 'ide' ),
'slug'           => 'masters'
),

    array(
        'supports'  => array( 'title', 'editor', 'thumbnail', 'excerpt',
'custom-fields', 'comments', 'page-attributes' ),
        'menu_icon' => 'dashicons-portfolio',
        'hierarchical' => true // just the addition of this
    )
);

$master -> register_taxonomy(
array(
'taxonomy_name' => 'masters_tags',
'singular'      => __( 'Master Tag', 'ide-cesem' ),
'plural'        => __( 'Masters Tags', 'ide-cesem' ),
'slug'          => 'masters-tag'
)
);

2015-09-14 12:25 GMT+02:00 Joe Grainger <notifications@github.com>:

**Comment by RaulGomezFrontEnd** [comment]
It works!!! 😁

Ok the FTP didn´t upload the file properly, my mistake.

Thank u so much for the help.

2015-09-14 12:30 GMT+02:00 Raul Gomez <raul00gm@gmail.com>:

**Comment by jjgrainger** [comment]
No worries!

:)
