### ISSUE TITLE
post type to enable in wp-api

### ISSUE THREAD

**Issue by lgt** [jjgrainger/wp-custom-post-type-class#46]
I just read that wp-api 2 does not  supports from default custom type. This one needs to be enabled by passed $args like `'show_in_rest'       => true,`. How would I do that?

**Comment by jjgrainger** [comment]
Sorry I don't quite understand, I'm not very familiar with WP-API, could you give me the link to what you're referring to so I can look into it.

Thanks :)

**Comment by jjgrainger** [comment]
I just did a quick search,

I believe you just need to add it to the second parameter when creating the post type, for example

```php
$books = new CPT('book', array(
    'show_in_rest' => true
));
```

**Comment by lgt** [comment]
I got it between thank you. Great Class!

**Comment by jjgrainger** [comment]
No problem and thanks! :)
