### ISSUE TITLE
Class isn't working with php 5.2.17 version. 

### ISSUE THREAD

**Issue by musamamasood** [jjgrainger/wp-custom-post-type-class#48]
Hello,

You class is not supported with 5.2.17 version but WordPress support it. So please help out to fix this for 5.2.17 php version.

**Comment by jjgrainger** [comment]
Hi @musamamasood,

Sorry for the delay, could you possibly provide a little more information. Is there anything in particular thats not working? Any error messages? What version of WordPress are you using?

Any information to help narrow down the problem will be much appreciated,

Thanks :)

**Comment by musamamasood** [comment]
Hello Joe Grainger, 
This is one of wonderful class to create custom post type and taxonomy. I have used that class in two plugins recently. I am also willing to contribute in this class, please guide me how I can do this. I have also suggestion to add functionality to create custom field. 

I had figured out above issue by version compare check to load class as php 5.2.17 didn't supported composer and this is not a your class bug. 

<code>version_compare(PHP_VERSION, '5.3.0') >= 0</code>

**Comment by QWp6t** [comment]
You should get off of PHP 5.2. There is no good reason to be using it.

**Comment by QWp6t** [comment]
But if you insist on using PHP 5.2 with composer, then you can get a 5.2-compatible autoloader by requiring the following...

`composer require xrstf/composer-php52`

For more information, see here: https://bitbucket.org/xrstf/composer-php52
