### ISSUE TITLE
Setting labels

### ISSUE THREAD

**Issue by mmjaeger** [jjgrainger/wp-custom-post-type-class#56]
hello
I was wondering whether it is possible to set some labels as well so I could have something like "All Books"?

Thanks

**Comment by jjgrainger** [comment]
You can set the labels using the second parameter passed when creating a post type.

```php
$books = new CPT('book', array(
    'labels' => array(
         'all_items' => 'All Books'
    )
));
```

For more label options see the WordPress Codex http://codex.wordpress.org/Function_Reference/register_post_type
