### ISSUE TITLE
Add menu_position

### ISSUE THREAD

**Issue by WebbizAdmin** [jjgrainger/wp-custom-post-type-class#59]
Tried to add the CPT higher on the menu. 

    function menu_position( $position = 5) {
        $this->options["menu_position"] = $position;
    }

This works.

**Comment by jjgrainger** [comment]
This is achievable with the options passed when creating the post typ:

```php
$books = new CPT('book', array(
    'menu_position' => 5
));
```

But I can see how adding an additional method may be useful. I'll consider it in the next release.

Thanks :) :+1:

**Comment by WebbizAdmin** [comment]
Ah ok, is there any difference in what I have done? is it better to do your route?

Thanks
Jason

**Comment by jjgrainger** [comment]
@WebbizAdmin No, they both pretty much achieve the same thing with the same option, just a slightly different way. Just the version I've provided is already available.

I think you're onto a winner, the options passed when creating the post type is quite a [large array](https://codex.wordpress.org/Function_Reference/register_post_type#Parameters), so it could be useful to break it up with some additional methods in the class. For example `labels()` could be another one.

**Comment by WebbizAdmin** [comment]
Cool, Great class you created by the way!
