### ISSUE TITLE
How do I add field price

### ISSUE THREAD

**Issue by nhantam** [jjgrainger/wp-custom-post-type-class#66]
Thank you your Class. It's very well done

I want to add some fields, example price

How do I add field price ?

Thanks & Regards

**Comment by jjgrainger** [comment]
You can't create custom fields with the class, instead I'd recommend using something like [Advanced Custom Fields](http://advancedcustomfields.com) to do this.

It's much easier and far more powerful than anything this class could do!

**Comment by nhantam** [comment]
Your class is great. Thank jjgrainger very much

I have just using other class to create custome field
