### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by nhantam** [jjgrainger/wp-custom-post-type-class#68]
How do I add category for custom post type ? It's similar Posts/Category

Thanks & Regards

**Comment by jjgrainger** [comment]
If it's the default WordPress category, you just need to pass the category name `category` to the `register_taxonomy` method like so

```php
$my_cpt->register_taxonomy('category');
```

Thanks :)

**Comment by nhantam** [comment]
Thank you very much
Regards
